apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    name: {name}
    app: geodescriber
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "geodescriber"
        effect: "NoSchedule"
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "4501"
          - name: ENVIRONMENT
            value: prod
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:4501
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: EE_PRIVATE_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: EE_PRIVATE_KEY

          - name: REDIS_URL
            value: redis://localhost:6379
        ports:
          - containerPort: 4501

      - name: redis
        image: redis
        ports:
         - containerPort: 6379
        resources:
         requests:
           memory: "0Mi"
           cpu: "0m"


      restartPolicy: Always
