apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: default
  name: geodescriber
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: geodescriber
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
